### ISSUE TITLE
Consider a different static site generator

### ISSUE THREAD

**Issue by svenluijten** [decahedronio/decahedron.io#1]
Should we not use [jigsaw](http://jigsaw.tighten.co) instead? Keep it 10x.

**Comment by cwhite92** [comment]
I'm happy to use whatever, the theme we found was a Jekyll one :)

One problem I've had with jigsaw is that it doesn't support dynamic things like a posts list, but I don't know if we're even going to have posts.

Might be nice to collaborate on a nicer site somewhere down the line.

**Comment by svenluijten** [comment]
Another possible option is [katana](https://github.com/themsaid/katana), which _does_ support dynamic content.

**Comment by phroggyy** [comment]
It doesn't really matter tbh. Get it up first, change it down the line when we have to; now it's just apply a template and go

**Comment by svenluijten** [comment]
Fair enough. My main gripe with Jekyll is that it's horribly supported on Windows.

**Comment by pleckey** [comment]
@svenluijten it's really a placeholder for now ... if (when) this actually gets going, we'll collaborate on a real site

**Comment by cwhite92** [comment]
WE SHOULD USE HUGO BECAUSE IT'S WRITTEN IN GO AND IS TOTALLY WEBSCALE FOR THAT REASON

**Comment by pleckey** [comment]
you're fired
